### ISSUE TITLE
Save Custom Meta Data: Content Creator / Software, etc.

### ISSUE THREAD

**Issue by makakaorg** [yasirkula/UnityTextureOps#3]
When saving Image is it possible to save additional metadata?

- Content Creator/CreatorTool (Software) (e.g. Photoshop writes here next: "Adobe Photoshop CC 2020 (Macintosh)")
- Author
- etc...

If there is no opportunity then it is feature request.
It's also actual for NativeGallery.

**Comment by yasirkula** [comment]
I had [some experience](https://github.com/yasirkula/Unity360ScreenshotCapture/blob/9a85e318da015d029af07dd8947cc911beab33a1/Plugins/Simple360Render/I360Render.cs#L83-L260) with inserting XMP metadata to JPEG/PNG files without using any 3rd party libraries. It was really hard to get right. I am honestly not planning to add metadata support for this reason.

There seems to be some built-in C# classes used for this task but they use either System.Drawing or System.Windows, so they will work on Windows only. There may be .NET libraries on GitHub for this task but then, instead of me integrating them to this plugin and having to include their license in the project, it would be better to let users import those libraries to their projects themselves and use the library's own API.
